export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';

export const SIGUIENTES_PRODUCTOS = 'SIGUIENTES_PRODUCTOS';

export const ANTERIORES_PRODUCTOS = 'ANTERIORES_PRODUCTOS';

export const PARA_FILTRAR_USADOS = 'PARA_FILTRAR_USADOS';

export const PARA_FILTRAR_NUEVOS = 'PARA_FILTRAR_NUEVOS';

export const SIGUIENTES_PRODUCTOS_FILTRADOS = 'SIGUIENTES_PRODUCTOS_FILTRADOS';

export const ANTERIORES_PRODUCTOS_FILTRADOS = 'ANTERIORES_PRODUCTOS_FILTRADOS'; 

export const PARA_FILTRAR_MENOR_PRECIO = 'PARA_FILTRAR_MENOR_PRECIO';

export const PARA_FILTRAR_MAYOR_PRECIO = 'PARA_FILTRAR_MAYOR_PRECIO';